### ISSUE TITLE
Demo not working on Firefox

### ISSUE THREAD

**Issue by jameyg** [dahliaOS/website#46] opened 2022-02-25 10:43 UTC
**Describe the bug**
It works on Chrome but not Firefox: https://web.dahliaos.io/

**What kind of a bug is it?**
Functional

**To Reproduce**
1. Go to https://web.dahliaos.io/ on Firefox (64-bit, v97.0 on Linux).
2. It will show a blank white page.
3. Open the JS console, this is the error I see:

```
Uncaught Error: TypeError: 3: type 'minified:tc' is not a subtype of type 'String'
    c https://web.dahliaos.io/main.dart.js:4669
    b4 https://web.dahliaos.io/main.dart.js:5352
    T8 https://web.dahliaos.io/main.dart.js:29747
    s https://web.dahliaos.io/main.dart.js:5873
    $2 https://web.dahliaos.io/main.dart.js:43577
    $1 https://web.dahliaos.io/main.dart.js:43571
    pt https://web.dahliaos.io/main.dart.js:44638
    $0 https://web.dahliaos.io/main.dart.js:43967
    AZ https://web.dahliaos.io/main.dart.js:5997
    oc https://web.dahliaos.io/main.dart.js:43899
    cY https://web.dahliaos.io/main.dart.js:43566
    N https://web.dahliaos.io/main.dart.js:5863
    AF https://web.dahliaos.io/main.dart.js:92365
    s https://web.dahliaos.io/main.dart.js:5873
    $2 https://web.dahliaos.io/main.dart.js:43577
    $1 https://web.dahliaos.io/main.dart.js:43571
    pt https://web.dahliaos.io/main.dart.js:44638
    $0 https://web.dahliaos.io/main.dart.js:43967
    AZ https://web.dahliaos.io/main.dart.js:5997
    oc https://web.dahliaos.io/main.dart.js:43899
    cY https://web.dahliaos.io/main.dart.js:43566
    N https://web.dahliaos.io/main.dart.js:5863
    qf https://web.dahliaos.io/main.dart.js:92353
    s https://web.dahliaos.io/main.dart.js:5873
    $2 https://web.dahliaos.io/main.dart.js:43577
    $1 https://web.dahliaos.io/main.dart.js:43571
    pt https://web.dahliaos.io/main.dart.js:44638
    $0 https://web.dahliaos.io/main.dart.js:43967
    AZ https://web.dahliaos.io/main.dart.js:5997
    oc https://web.dahliaos.io/main.dart.js:43899
    cY https://web.dahliaos.io/main.dart.js:43566
    N https://web.dahliaos.io/main.dart.js:5863
    vD https://web.dahliaos.io/main.dart.js:91699
    s https://web.dahliaos.io/main.dart.js:5873
    $2 https://web.dahliaos.io/main.dart.js:43577
    $1 https://web.dahliaos.io/main.dart.js:43571
    pt https://web.dahliaos.io/main.dart.js:44638
    $0 https://web.dahliaos.io/main.dart.js:43967
    AZ https://web.dahliaos.io/main.dart.js:5997
    oc https://web.dahliaos.io/main.dart.js:43899
    $0 https://web.dahliaos.io/main.dart.js:43934
    bes https://web.dahliaos.io/main.dart.js:6029
    bf4 https://web.dahliaos.io/main.dart.js:6031
    $1 https://web.dahliaos.io/main.dart.js:43521
    bhh https://web.dahliaos.io/main.dart.js:4750
    s https://web.dahliaos.io/main.dart.js:4758
```

**Expected behavior**
The demo works.

**Screenshots**

![Screenshot from 2022-02-25 10-42-14](https://user-images.githubusercontent.com/752314/155701575-44cb3f16-043b-4f89-ac91-2c40a7801f63.png)

**Browser (please complete the following information):**

Firefox 97.0 on Ubuntu 20.04.3 LTS.

**Additional context**

I disabled all Firefox add-ons, so a completely fresh browser.

**Comment by larsb24** [comment] 2022-02-25 10:45
Haven't experienced that issue before, it's very odd... I will look into it later. 
For the time being could you try opening it in a in-private tab so we can ensure that it's not a database corruption?

**Comment by NusryNizam** [comment] 2022-02-25 12:23
Working for me.
Firefox 97.0 on Ubuntu 21.10

**Comment by larsb24** [comment] 2022-02-25 22:30
> **Describe the bug** It works on Chrome but not Firefox: [web.dahliaos.io](https://web.dahliaos.io/)
> 
> **What kind of a bug is it?** Functional
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to [web.dahliaos.io](https://web.dahliaos.io/) on Firefox (64-bit, v97.0 on Linux).
> 2. It will show a blank white page.
> 3. Open the JS console, this is the error I see:
> 
> ```
> Uncaught Error: TypeError: 3: type 'minified:tc' is not a subtype of type 'String'
>     c https://web.dahliaos.io/main.dart.js:4669
>     b4 https://web.dahliaos.io/main.dart.js:5352
>     T8 https://web.dahliaos.io/main.dart.js:29747
>     s https://web.dahliaos.io/main.dart.js:5873
>     $2 https://web.dahliaos.io/main.dart.js:43577
>     $1 https://web.dahliaos.io/main.dart.js:43571
>     pt https://web.dahliaos.io/main.dart.js:44638
>     $0 https://web.dahliaos.io/main.dart.js:43967
>     AZ https://web.dahliaos.io/main.dart.js:5997
>     oc https://web.dahliaos.io/main.dart.js:43899
>     cY https://web.dahliaos.io/main.dart.js:43566
>     N https://web.dahliaos.io/main.dart.js:5863
>     AF https://web.dahliaos.io/main.dart.js:92365
>     s https://web.dahliaos.io/main.dart.js:5873
>     $2 https://web.dahliaos.io/main.dart.js:43577
>     $1 https://web.dahliaos.io/main.dart.js:43571
>     pt https://web.dahliaos.io/main.dart.js:44638
>     $0 https://web.dahliaos.io/main.dart.js:43967
>     AZ https://web.dahliaos.io/main.dart.js:5997
>     oc https://web.dahliaos.io/main.dart.js:43899
>     cY https://web.dahliaos.io/main.dart.js:43566
>     N https://web.dahliaos.io/main.dart.js:5863
>     qf https://web.dahliaos.io/main.dart.js:92353
>     s https://web.dahliaos.io/main.dart.js:5873
>     $2 https://web.dahliaos.io/main.dart.js:43577
>     $1 https://web.dahliaos.io/main.dart.js:43571
>     pt https://web.dahliaos.io/main.dart.js:44638
>     $0 https://web.dahliaos.io/main.dart.js:43967
>     AZ https://web.dahliaos.io/main.dart.js:5997
>     oc https://web.dahliaos.io/main.dart.js:43899
>     cY https://web.dahliaos.io/main.dart.js:43566
>     N https://web.dahliaos.io/main.dart.js:5863
>     vD https://web.dahliaos.io/main.dart.js:91699
>     s https://web.dahliaos.io/main.dart.js:5873
>     $2 https://web.dahliaos.io/main.dart.js:43577
>     $1 https://web.dahliaos.io/main.dart.js:43571
>     pt https://web.dahliaos.io/main.dart.js:44638
>     $0 https://web.dahliaos.io/main.dart.js:43967
>     AZ https://web.dahliaos.io/main.dart.js:5997
>     oc https://web.dahliaos.io/main.dart.js:43899
>     $0 https://web.dahliaos.io/main.dart.js:43934
>     bes https://web.dahliaos.io/main.dart.js:6029
>     bf4 https://web.dahliaos.io/main.dart.js:6031
>     $1 https://web.dahliaos.io/main.dart.js:43521
>     bhh https://web.dahliaos.io/main.dart.js:4750
>     s https://web.dahliaos.io/main.dart.js:4758
> ```
> 
> **Expected behavior** The demo works.
> 
> **Screenshots**
> 
> ![Screenshot from 2022-02-25 10-42-14](https://user-images.githubusercontent.com/752314/155701575-44cb3f16-043b-4f89-ac91-2c40a7801f63.png)
> 
> **Browser (please complete the following information):**
> 
> Firefox 97.0 on Ubuntu 20.04.3 LTS.
> 
> **Additional context**
> 
> I disabled all Firefox add-ons, so a completely fresh browser.

I just tried it on my machine and I cannot reproduce the error. As I said, maybe give it a try in an in-private tab to see if it has anything to do with the database.

**Comment by jameyg** [comment] 2022-03-03 13:25
@larsb24 @NusryNizam Unfortunately it still doesn't work. In a private session:

![Screenshot from 2022-03-03 13-24-57](https://user-images.githubusercontent.com/752314/156573597-ba2686e1-a027-4de2-8078-5626313ba4dc.png)

I disabled all add-ons.

**Comment by larsb24** [comment] 2022-03-03 20:43
That is weird, I will look into it but I don't really know what to do because I can't reproduce the error

**Comment by SincerelyFaust** [comment] 2022-05-31 17:33
Closing as the issue was opened in the wrong repository, this is Pangolin related, please file the issue there instead.

**Closed by SincerelyFaust** 2022-05-31 17:33 UTC
